// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SafeGuardAPI.Connection;

#nullable disable

namespace SafeGuardAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SafeGuardAPI.Models.Alerta", b =>
                {
                    b.Property<int>("IdAlerta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ALERTA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlerta"));

                    b.Property<DateTime>("DataAlerta")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_ALERTA");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("MENSAGEM");

                    b.Property<int>("RiscoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_RISCO");

                    b.HasKey("IdAlerta");

                    b.ToTable("TB_ALERTA", (string)null);
                });

            modelBuilder.Entity("SafeGuardAPI.Models.Estacao", b =>
                {
                    b.Property<int>("IdEstacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ESTACAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstacao"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUS");

                    b.HasKey("IdEstacao");

                    b.ToTable("TB_ESTACAO", (string)null);
                });

            modelBuilder.Entity("SafeGuardAPI.Models.Leitura", b =>
                {
                    b.Property<int>("IdLeitura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_LEITURA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLeitura"));

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_HORA");

                    b.Property<int>("SensorId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SENSOR");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VALOR");

                    b.HasKey("IdLeitura");

                    b.ToTable("TB_LEITURA", (string)null);
                });

            modelBuilder.Entity("SafeGuardAPI.Models.Risco", b =>
                {
                    b.Property<int>("IdRisco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_RISCO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRisco"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("DESCRICAO");

                    b.Property<int>("IdEstacao")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ESTACAO");

                    b.Property<int>("Nivel")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NIVEL");

                    b.HasKey("IdRisco");

                    b.ToTable("TB_RISCO", (string)null);
                });

            modelBuilder.Entity("SafeGuardAPI.Models.Sensor", b =>
                {
                    b.Property<int>("IdSensor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_SENSOR");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSensor"));

                    b.Property<int>("EstacaoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ESTACAO");

                    b.Property<string>("TipoSensor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("TIPO_SENSOR");

                    b.HasKey("IdSensor");

                    b.ToTable("TB_SENSOR", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
